language: node_js
node_js:
  - '0.10'

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD
  - 'npm install -g bower grunt-cli'

script:
  - 'npm install'
  - 'bower install'
  - 'grunt'
  - 'grunt ngdocs:publish'

after_success:
  - sh -x ./scripts/publish.sh

deploy:
  provider: openshift
  user: "$OPENSHIFT_USER"
  password: "$OPENSHIFT_PWD"
  domain: "patternfly"
  app: angular
  skip_cleanup: true
  on:
    branch: master-dist
    condition: $TRAVIS_REPO_SLUG = "patternfly/angular-patternfly"

notifications:
  email:
    - patternfly-build@redhat.com
